#!/bin/bash
# =============================================================================
# Soup (roadmap #58, checklist item 3: automated evaluation before any
# promotion decision).
#
# HONEST HARDWARE NOTE (read this before running): 01_setup_base.sh
# already runs the text model at --gpu-memory-utilization 0.6, vision
# at 0.25, embedding at 0.1 - 0.95 total on a single GPU box. There is
# no room to run a candidate ~30B model SIDE BY SIDE with the
# production one. This script does NOT attempt that. Instead it walks
# you through an ATTENDED maintenance window: you stop the production
# vllm process yourself (per the GOLDEN RULE in 01_setup_base.sh -
# Ctrl+C, never kill -9), this script starts the candidate on the SAME
# port temporarily, runs the real evaluation suites against it, then
# you stop the candidate and restart production yourself. Nothing here
# starts or stops the production process automatically - that is
# exactly the "manual, not automatic" boundary the checklist asked for
# applied one step earlier than promotion itself, because on this
# hardware, EVALUATING a candidate already requires taking production
# offline for a few minutes, not just promoting one.
#
# WHAT ACTUALLY GATES THE PASS/FAIL: 11_evaluation_suite.py, because it
# is the ONE script in this project that is a genuine external HTTP
# client hitting /api/chat - i.e. it is the only existing test that
# actually calls the fine-tuned model at all (see its own docstring).
# 05_acceptance_tests.py is also run and included in the report for
# completeness (it's part of the project's standard go/no-go pair per
# 08_deployment_checklist.sh), but it calls Odoo tool methods DIRECTLY
# and never touches the LLM - it cannot regress based on which model is
# running, so it is reported as informational here, not a candidate-
# specific gate. Wiring it in as if it tested the model would be
# misleading, not thorough.
#
# Usage:
#   ./23_soup_evaluate_candidate.sh /opt/soup-workspace/candidates/<timestamp>
# =============================================================================
set -euo pipefail

CANDIDATE_DIR="${1:?Usage: $0 <candidate-adapter-dir>}"
if [ ! -d "$CANDIDATE_DIR" ]; then
  echo "Candidate directory not found: $CANDIDATE_DIR"
  exit 1
fi

REPORT_DIR="${SOUP_REPORTS_DIR:-/opt/soup-workspace/reports}"
mkdir -p "$REPORT_DIR"
TIMESTAMP="$(date +%Y%m%d-%H%M%S)"
REPORT_FILE="${REPORT_DIR}/candidate-eval-${TIMESTAMP}.txt"
CANDIDATE_SCRIPT="/opt/start_vllm_candidate.sh"

cat > "$CANDIDATE_SCRIPT" << VLLMEOF
#!/bin/bash
# Generated by 23_soup_evaluate_candidate.sh on ${TIMESTAMP}.
# Serves the SAME base checkpoint as /opt/start_vllm.sh, with the
# candidate LoRA adapter added, on the SAME port (8000) so the
# existing llm.provider record (llm_agent_data.xml) needs no change.
source /opt/vllm/bin/activate
export HF_HOME=/workspace/hf_cache
vllm serve cpatonn/Qwen3-30B-A3B-Instruct-2507-AWQ \\
  --host 127.0.0.1 --port 8000 \\
  --enable-auto-tool-choice --tool-call-parser hermes \\
  --served-model-name local-model \\
  --max-model-len 131072 \\
  --gpu-memory-utilization 0.6 \\
  --enable-lora --lora-modules candidate=${CANDIDATE_DIR}
VLLMEOF
chmod +x "$CANDIDATE_SCRIPT"

echo "============================================================"
echo " ATTENDED MANUAL STEP - this is deliberate, read fully"
echo "============================================================"
echo "1. Go to the terminal/session currently running /opt/start_vllm.sh"
echo "   and stop it gracefully: Ctrl+C, then WAIT for it to fully exit"
echo "   (see the GOLDEN RULE in 01_setup_base.sh - never kill -9)."
echo "2. In a separate session, start the candidate server:"
echo "     $CANDIDATE_SCRIPT"
echo "3. Wait until it logs that it's ready to serve (same startup"
echo "   message you'd see from the normal start_vllm.sh)."
echo ""
read -rp "Press Enter once the CANDIDATE server is up and serving on :8000... "

echo ""
echo "=== Health-checking candidate server on :8000 ==="
for i in $(seq 1 30); do
  if curl -sf http://127.0.0.1:8000/v1/models >/dev/null 2>&1; then
    echo "Candidate server is responding."
    break
  fi
  if [ "$i" = "30" ]; then
    echo "Candidate server never responded on :8000 - aborting without"
    echo "touching anything else. Restart your real /opt/start_vllm.sh now."
    exit 1
  fi
  sleep 2
done

{
  echo "Soup candidate evaluation report"
  echo "Candidate: $CANDIDATE_DIR"
  echo "Timestamp: $TIMESTAMP"
  echo ""
  echo "--- HARD GATE: 11_evaluation_suite.py (real HTTP calls to /api/chat," \
       "actually exercises the candidate model) ---"
} | tee "$REPORT_FILE"

HARD_EXIT=0
./11_evaluation_suite.sh 2>&1 | tee -a "$REPORT_FILE" || HARD_EXIT=$?

{
  echo ""
  echo "--- INFORMATIONAL: 05_acceptance_tests.py (Odoo ACL only - calls" \
       "tool methods directly, never touches the LLM, cannot regress by" \
       "candidate model choice; included for completeness only, NOT part" \
       "of the pass/fail gate below) ---"
} | tee -a "$REPORT_FILE"

/opt/odoo/odoo-bin shell -c /opt/odoo.conf -d company_ai \
  < 05_acceptance_tests.py 2>&1 | tee -a "$REPORT_FILE" || true

if [ "$HARD_EXIT" -eq 0 ]; then
  echo "SOUP_CANDIDATE_EVAL: PASS" | tee -a "$REPORT_FILE"
else
  echo "SOUP_CANDIDATE_EVAL: FAIL" | tee -a "$REPORT_FILE"
fi

echo ""
echo "============================================================"
echo " ATTENDED MANUAL STEP - read fully before doing anything else"
echo "============================================================"
echo "1. Stop the CANDIDATE server (Ctrl+C, wait for full exit)."
echo "2. Restart your real, unmodified /opt/start_vllm.sh."
echo "3. Report written to: $REPORT_FILE"
echo "4. This report is what 24_soup_promote_candidate.sh will require"
echo "   and parse - do not hand-edit it."
