{
    "name": "AI Business Tools",
    "version": "18.0.1.8.0",
    "summary": "Named, audited, role-safe LLM tools for leave approval, task "
                "delegation and role-scoped documents - replaces generic "
                "unrestricted ORM tools with explicit business actions",
    "category": "Technical",
    "depends": [
        "base", "hr", "hr_holidays", "hr_attendance", "project", "mail", "stock", "account", "mrp",
        "sales_team", "sale_management", "purchase",
        "llm", "llm_tool", "llm_assistant",
        "ai_gateway", "company_ai_demo",
    ],
    "data": [
        "security/ir.model.access.csv",
        "security/document_rules.xml",
        "data/role_templates_data.xml",
        "security/task_department_rules.xml",
        "security/access_grant_role_rules.xml",
        "security/approval_rules.xml",
        "data/tool_risk_data.xml",
        "data/approval_matrix_data.xml",
        "data/model_policy_data.xml",
        "data/escalation_config_data.xml",
        "data/cron_data.xml",
        "security/audit_log_rules.xml",
        "views/approval_views.xml",
        "views/access_grant_views.xml",
        "views/audit_log_views.xml",
        "views/role_permissions_views.xml",
        "views/scheduled_command_views.xml",
        "reports/hr_directory_report.xml",
    ],
    "installable": True,
    "application": False,
    "license": "LGPL-3",
}
